### ISSUE TITLE
Last letter of Drawer Items not visible on Oneplus devices

### ISSUE THREAD

**Issue by nakulBageja** [sarthakpranesh/Covid19#22]
Hi, I was trying your application on my phone with resolution of 1080 x 2340 And the dashboard options are not being displayed properly.

<img src="https://user-images.githubusercontent.com/39912882/107363937-d6a14f80-6b00-11eb-96fe-fdd8728dbc86.jpeg" width=100/>

**Comment by sarthakpranesh** [comment]
Hey @ketonium10, can you provide some more options regarding the device model and the Android version it is running. I came across such a bug previously, specifically on OnePlus devices where the last letter of each word was not being displayed. This issue looks similar to that one, and it'll be a huge help if you can provide the model and android version.

**Comment by ketonium10** [comment]
Yes, it  is OnePlus 7 Android version 10

**Comment by sarthakpranesh** [comment]
Ah, I see. It seems this issue is being produced due to this [bug/issue](https://github.com/facebook/react-native/issues/15114#issuecomment-335797756) caused due to incompatible fonts. I did fix this issue in a previous release, but I guess somewhere down the line while refactoring it reappeared and I missed it. Thanks again, I'll fix this soon :+1:

**Comment by ketonium10** [comment]
Glad to help. Working on React native myself, will surely keep following this project and help you guys 👍

**Comment by sarthakpranesh** [comment]
Hey again @nakulBageja, I hope you are doing well. We are now shipping `Roboto` along with our app. I have not yet made a new release because I wasn't able to test this issue ( wasn't able to get an OnePlus device ). I'll be pleased if you can test the latest builds found [here](https://github.com/sarthakpranesh/Covid19/tree/build) and let me know if the issue is resolved.

Apart from this, now the project is also extended to the web platform. Do check it out at: https://covid19rn.vercel.app/

**Comment by nakulBageja** [comment]
@sarthakpranesh Hey, I'm doing well. Surely, I will check it out and let you know. Will check out the web version too👍
